const TEST_CONSTANT = ''

const DEVICE_OEM_MODEL_TO_HOLD_DATA = 'Cloud_Thing'
const OEM_MODEL_CAMERA_NODE = 'ggdemo_camera'
const OEM_MODEL_DOOR_SENSOR = '3323-G'
const OEM_MODEL_DOOR_SENSOR_2 = 'TS0203'
const OEM_MODEL_LINUX_EVB = 'linuxevb'
const OEM_MODEL_MOTION_SENSOR = '3328-G'
const OEM_MODEL_MOTION_SENSOR_2 = 'TS0202'
const OEM_MODEL_TEMPERATURE_SENSOR = '3310-G'
const OEM_MODEL_TEMPERATURE_SENSOR_2 = 'RH3052'
const OEM_MODEL_THERMOSTAT_SENSOR = '3157100'
const OEM_MODEL_WATER_LEAK_SENSOR = '3315-G'
const OEM_SMART_LOCK_SENSOR = '5510-G' // Note. Temporal OEM model
const OEM_MODEL_SALAS_THERMOSTAT_SENSOR = 'ST898ZB'

// Auth constants
const AUTHORIZATION_HEADER = 'Authorization'
const ACCESS_TOKEN_KEY = 'accessToken'
const TOKEN_PREFIX = 'auth_token'

// HMAC constants
const HDR_SSO_DATE = 'x-sso-date'
const HDR_AYLA_ORIGIN_HOST = 'x-ayla-origin-host'

// Device property names
const DEVICE_PROPERTY_BASE_TYPE_FILE = 'file'

const THERMOSTAT_DATA_POINT = {
  COOL_SETPOINT_READ: 'dev:thermost:cooling_setpoint',
  HEAT_SETPOINT_READ: 'dev:thermost:heating_setpoint',
  LOCAL_TEMP: 'dev:thermost:local_temperature',
}

module.exports = {
  TEST_CONSTANT,
  AUTHORIZATION_HEADER,
  ACCESS_TOKEN_KEY,
  TOKEN_PREFIX,
  DEVICE_OEM_MODEL_TO_HOLD_DATA,
  OEM_MODEL_CAMERA_NODE,
  OEM_MODEL_DOOR_SENSOR,
  OEM_MODEL_DOOR_SENSOR_2,
  OEM_MODEL_LINUX_EVB,
  OEM_MODEL_MOTION_SENSOR,
  OEM_MODEL_MOTION_SENSOR_2,
  OEM_MODEL_TEMPERATURE_SENSOR,
  OEM_MODEL_TEMPERATURE_SENSOR_2,
  OEM_MODEL_THERMOSTAT_SENSOR,
  OEM_MODEL_WATER_LEAK_SENSOR,
  OEM_SMART_LOCK_SENSOR,
  OEM_MODEL_SALAS_THERMOSTAT_SENSOR,
  HDR_SSO_DATE,
  HDR_AYLA_ORIGIN_HOST,
  DEVICE_PROPERTY_BASE_TYPE_FILE,
  THERMOSTAT_DATA_POINT,
}
